name: Setup Ruby Manually

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl build-essential libssl-dev libreadline-dev zlib1g-dev

      - name: Install ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          sudo ./ruby-build/install.sh

      - name: Install Ruby 3.1.4
        run: |
          sudo mkdir -p /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo ruby-build 3.1.4 /opt/hostedtoolcache/Ruby/3.1.4/x64

      - name: Mark Ruby as installed
        run: |
          sudo touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Add Ruby to PATH
        run: echo "/opt/hostedtoolcache/Ruby/3.1.4/x64/bin" >> $GITHUB_PATH

      - name: Check Ruby version
        run: ruby -v
